name: Update 3D Profile Contribution

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub-Profile-3D-Contrib
        uses: yoshi389111/github-profile-3d-contrib@0.9.0
